"use client";

import { useEffect, useState } from "react";
import { fetchCollection } from "@/lib/api";
import type { ApiRecord } from "@/lib/types";
import { PageHeader } from "@/components/page-header";
import { StatCard } from "@/components/stat-card";
import { DataTable } from "@/components/data-table";

type DashboardState = {
  leads: ApiRecord[];
  visits: ApiRecord[];
  invoices: ApiRecord[];
  clinics: ApiRecord[];
};

export default function DashboardPage() {
  const [state, setState] = useState<DashboardState>({
    leads: [],
    visits: [],
    invoices: [],
    clinics: [],
  });
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    async function load() {
      try {
        const [leads, visits, invoices, clinics] = await Promise.all([
          fetchCollection<ApiRecord>("/leads"),
          fetchCollection<ApiRecord>("/visits"),
          fetchCollection<ApiRecord>("/invoices"),
          fetchCollection<ApiRecord>("/clinics"),
        ]);

        setState({ leads, visits, invoices, clinics });
      } catch (err) {
        setError(err instanceof Error ? err.message : "Unable to load dashboard.");
      }
    }

    load();
  }, []);

  return (
    <div className="space-y-6">
      <PageHeader
        title="Operations Dashboard"
        description="A fast read on pipeline volume, clinic activity, appointments, and billing pulled live from the backend."
      />

      {error ? (
        <div className="rounded-2xl border border-rose-200 bg-rose-50 px-5 py-4 text-sm text-rose-700">
          {error}
        </div>
      ) : null}

      <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
        <StatCard label="Active Leads" value={state.leads.length} hint="Current CRM records visible to your role." />
        <StatCard label="Scheduled Visits" value={state.visits.length} hint="Appointments and visit lifecycle entries." />
        <StatCard label="Invoices" value={state.invoices.length} hint="Billing records generated by treatment and visits." />
        <StatCard label="Clinics" value={state.clinics.length} hint="Branches configured in the backend workspace." />
      </div>

      <div className="grid gap-6 xl:grid-cols-2">
        <DataTable
          title="Recent Leads"
          description="Lead pipeline entries coming from the CRM module."
          rows={state.leads.slice(0, 6)}
          preferredKeys={["id", "name", "phone", "platform", "lead_status_id"]}
        />
        <DataTable
          title="Recent Visits"
          description="Operational scheduling and visit outcomes."
          rows={state.visits.slice(0, 6)}
          preferredKeys={["id", "lead_id", "clinic_id", "scheduled_date", "status", "total_cost"]}
        />
      </div>
    </div>
  );
}
